### ISSUE TITLE
[Bug] Exception thrown when serializing NameError exceptions using Psych

### ISSUE THREAD

**Issue by arkadiyt** [aws/aws-flow-ruby#23]
Steps to reproduce:

```
begin
  abc
rescue Exception => ex
  converter = AWS::Flow::YAMLDataConverter.new
  converter.load(converter.dump(ex))
end
```

Output:

```
TypeError: allocator undefined for NameError::message
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:303:in `allocate'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:303:in `revive'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:178:in `visit_Psych_Nodes_Mapping'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/visitor.rb:15:in `visit'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/visitor.rb:5:in `accept'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:20:in `accept'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:210:in `block in visit_Psych_Nodes_Mapping'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:210:in `map'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:210:in `visit_Psych_Nodes_Mapping'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/visitor.rb:15:in `visit'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/visitor.rb:5:in `accept'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:20:in `accept'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:240:in `visit_Psych_Nodes_Document'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/visitor.rb:15:in `visit'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/visitor.rb:5:in `accept'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:20:in `accept'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych/nodes/node.rb:35:in `to_ruby'
        from /home/arkadiy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych.rb:130:in `load'
        from /home/arkadiy/code/cardspring/core/vendor/bundle/ruby/2.0.0/gems/aws-flow-1.0.5/lib/aws/decider/data_converter.rb:30:in `load'
        from (irb):5:in `rescue in irb_binding'
        from (irb):1
```

This is actually a bug in Psych (see https://github.com/tenderlove/psych/issues/85), but since it's been open for more than a year it would be nice if the flows gem worked around it

**Comment by david-gregory-inmar** [comment]
Any update on this issue?
