### ISSUE TITLE
Booking example fails with NoContextException

### ISSUE THREAD

**Issue by mojodna** [aws/aws-flow-ruby#90]
With no changes to the sample code from http://docs.aws.amazon.com/amazonswf/latest/awsrbflowguide/basic-workflow.html, I get the follow error when running the workers:

```bash
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
$ aws-flow-ruby -f worker.json
waiting on workers [76262, 76263, 76264, 76265, 76266, 76267, 76268, 76269, 76271, 76272, 76273, 76274] to complete
Workflow has started
Reserving a car for customer
Reserving air ticket
Waiting for reservation to complete
/Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/flow/implementation.rb:38:in `task': AWS::Flow::Core::NoContextException (AWS::Flow::Core::NoContextException)
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:293:in `rescue in respond_activity_task_failed'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:280:in `respond_activity_task_failed'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:204:in `respond_activity_task_failed_with_retry'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:335:in `rescue in process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:338:in `process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:384:in `block in poll_and_process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:75:in `call'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:75:in `block in execute'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:68:in `fork'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:68:in `execute'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:384:in `poll_and_process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:442:in `run_once'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:415:in `block in start'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:414:in `loop'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:414:in `start'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:113:in `block (2 levels) in spawn_and_start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:111:in `fork'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:111:in `block in spawn_and_start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:110:in `times'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:110:in `spawn_and_start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:213:in `block in start_activity_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:187:in `each'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:187:in `start_activity_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:312:in `start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:406:in `run'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:424:in `main'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/bin/aws-flow-ruby:5:in `<top (required)>'
	from /Users/seth/src/tmp/aws-flow-ruby/aws-flow/aws-flow-ruby:16:in `load'
	from /Users/seth/src/tmp/aws-flow-ruby/aws-flow/aws-flow-ruby:16:in `<main>'
/Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/flow/implementation.rb:38:in `task': AWS::Flow::Core::NoContextException (AWS::Flow::Core::NoContextException)
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:293:in `rescue in respond_activity_task_failed'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:280:in `respond_activity_task_failed'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:204:in `respond_activity_task_failed_with_retry'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:335:in `rescue in process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:338:in `process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:384:in `block in poll_and_process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:75:in `call'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:75:in `block in execute'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:68:in `fork'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/executor.rb:68:in `execute'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/task_poller.rb:384:in `poll_and_process_single_task'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:442:in `run_once'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:415:in `block in start'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:414:in `loop'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:414:in `start'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:113:in `block (2 levels) in spawn_and_start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:111:in `fork'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:111:in `block in spawn_and_start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:110:in `times'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:110:in `spawn_and_start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:213:in `block in start_activity_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:187:in `each'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:187:in `start_activity_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:312:in `start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:406:in `run'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:424:in `main'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/bin/aws-flow-ruby:5:in `<top (required)>'
	from /Users/seth/src/tmp/aws-flow-ruby/aws-flow/aws-flow-ruby:16:in `load'
	from /Users/seth/src/tmp/aws-flow-ruby/aws-flow/aws-flow-ruby:16:in `<main>'
```

**Comment by mojodna** [comment]
Works with 2.1.5, fwiw:

```bash
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
```

**Comment by pmohan6** [comment]
Thanks for reporting the issue. I'll need to dig in a little here and see what's changed from 2.1.5 to 2.2.0. Will reply back once I have the root cause.

**Comment by pmohan6** [comment]
I've identified the root cause of NoContextException. It's getting thrown because of a bug in the ActivityTaskPoller. It got trigged due to the other issue you are seeing (missing activity definition). I'm working on root causing that as well.

**Comment by pmohan6** [comment]
I've a fix ready for this. Will release the patch soon.

**Comment by rmberg** [comment]
+1 would love to see this fix soon so we can use flow with ruby 2.2.0

**Comment by alhafoudh** [comment]
+1

**Comment by pmohan6** [comment]
https://github.com/aws/aws-flow-ruby/commit/b32e9e42f4deb71afd2cec307390fdcef837384c
https://github.com/aws/aws-flow-ruby/commit/f923dc1012383492732cddbdec02347d3bf24da1

**Comment by davidcpell** [comment]
This is closed but I'm still getting the same problem with Ruby 2.2.0 whenever I try to execute a workflow. Switching to Ruby 2.3.0 solved the issue on my end.  

`aws-flow` version 2.4.0

**Comment by syedrakib** [comment]
I am on ruby-2.3.3 with aws-flow-2.4.0
I am still getting this error today.
